// <auto-generated />
using System;
using FamilyAI.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FamilyAI.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FamilyAI.Domain.Models.ChatLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("EntryTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReply")
                        .HasColumnType("bit");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ThreadId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ThreadId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatLogs", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.GlobalFlagRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("GlobalFlagRules", "Chat");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Direct reference to suicide",
                            IsDeleted = false,
                            Type = 0,
                            Value = "suicide"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Self-harm phrase",
                            IsDeleted = false,
                            Type = 0,
                            Value = "kill myself"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Self-harm phrase",
                            IsDeleted = false,
                            Type = 0,
                            Value = "self harm"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Self-harm phrase",
                            IsDeleted = false,
                            Type = 0,
                            Value = "cutting myself"
                        },
                        new
                        {
                            Id = 5,
                            Description = "General drug reference",
                            IsDeleted = false,
                            Type = 0,
                            Value = "drugs"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Cannabis reference",
                            IsDeleted = false,
                            Type = 0,
                            Value = "marijuana"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Cannabis slang",
                            IsDeleted = false,
                            Type = 0,
                            Value = "weed"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Hard drug reference",
                            IsDeleted = false,
                            Type = 0,
                            Value = "cocaine"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Hard drug reference",
                            IsDeleted = false,
                            Type = 0,
                            Value = "heroin"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Hard drug reference",
                            IsDeleted = false,
                            Type = 0,
                            Value = "meth"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Hard drug reference",
                            IsDeleted = false,
                            Type = 0,
                            Value = "fentanyl"
                        },
                        new
                        {
                            Id = 12,
                            Description = "Alcohol reference",
                            IsDeleted = false,
                            Type = 0,
                            Value = "alcohol"
                        },
                        new
                        {
                            Id = 13,
                            Description = "Sharing personal location information",
                            IsDeleted = false,
                            Type = 0,
                            Value = "my address"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Sharing personal contact information",
                            IsDeleted = false,
                            Type = 0,
                            Value = "my phone number"
                        },
                        new
                        {
                            Id = 15,
                            Description = "Sharing school information with strangers",
                            IsDeleted = false,
                            Type = 0,
                            Value = "my school"
                        },
                        new
                        {
                            Id = 16,
                            Description = "Any discussion of self-harm, suicidal thoughts, or hurting oneself",
                            IsDeleted = false,
                            Type = 1,
                            Value = "Self-harm or suicide"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Discussion of using, obtaining, or glorifying drugs or alcohol",
                            IsDeleted = false,
                            Type = 1,
                            Value = "Drug or alcohol use"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Threats of violence, planning to hurt someone, or glorifying violence",
                            IsDeleted = false,
                            Type = 1,
                            Value = "Violence or physical threats"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Sexually explicit topics, pornography, or adult themes inappropriate for children",
                            IsDeleted = false,
                            Type = 1,
                            Value = "Sexual or adult content"
                        },
                        new
                        {
                            Id = 20,
                            Description = "Bullying others, being bullied, or discussions of targeted harassment",
                            IsDeleted = false,
                            Type = 1,
                            Value = "Bullying or harassment"
                        },
                        new
                        {
                            Id = 21,
                            Description = "Sharing home address, phone number, school name, or other identifying information",
                            IsDeleted = false,
                            Type = 1,
                            Value = "Sharing personal information"
                        },
                        new
                        {
                            Id = 22,
                            Description = "Adult asking child for personal info, photos, or to meet in person",
                            IsDeleted = false,
                            Type = 1,
                            Value = "Online predator or grooming behavior"
                        },
                        new
                        {
                            Id = 23,
                            Description = "Discussion of obtaining or using weapons",
                            IsDeleted = false,
                            Type = 1,
                            Value = "Weapons"
                        },
                        new
                        {
                            Id = 24,
                            Description = "Messages with a threatening, hostile, or intimidating tone directed at a person",
                            IsDeleted = false,
                            Type = 2,
                            Value = "Threatening or aggressive"
                        },
                        new
                        {
                            Id = 25,
                            Description = "Messages with a sexually suggestive or inappropriate tone for a child",
                            IsDeleted = false,
                            Type = 2,
                            Value = "Sexually suggestive"
                        },
                        new
                        {
                            Id = 26,
                            Description = "Messages expressing extreme despair, hopelessness, or emotional crisis",
                            IsDeleted = false,
                            Type = 2,
                            Value = "Deeply distressed or hopeless"
                        });
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.OllamaSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ModelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ModelUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("OllamaSettings", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ParentChild", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChildId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildId");

                    b.HasIndex("ParentId");

                    b.ToTable("ParentChildren", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ParentFlagRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("GlobalRuleId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalRuleId");

                    b.HasIndex("ParentUserId");

                    b.ToTable("ParentFlagRules", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ParentScanSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("ParentUserId")
                        .HasColumnType("int");

                    b.Property<int>("Sensitivity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentUserId");

                    b.ToTable("ParentScanSettings", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.PromptTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("PromptTemplates", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Roles", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ThreadFlagDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MatchedExcerpt")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int?>("MessageId")
                        .HasColumnType("int");

                    b.Property<int>("RuleType")
                        .HasColumnType("int");

                    b.Property<string>("RuleValue")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("ThreadScanResultId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ThreadScanResultId");

                    b.ToTable("ThreadFlagDetails", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ThreadModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("ThreadName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Threads", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ThreadScanResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AiSummary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsFlagged")
                        .HasColumnType("bit");

                    b.Property<string>("RuleSetHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("ScannedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ScannedByParentId")
                        .HasColumnType("int");

                    b.Property<int>("ThreadId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ScannedByParentId");

                    b.HasIndex("ThreadId");

                    b.ToTable("ThreadScanResults", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.UserModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Users", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.UserPermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserPermissions", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.UserSetting", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("PromptTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateId");

                    b.HasIndex("UserId");

                    b.ToTable("UserSettings", "Chat");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ChatLog", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.ThreadModel", "Thread")
                        .WithMany("ChatLogs")
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAI.Domain.Models.UserModel", "User")
                        .WithMany("ChatLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Thread");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ParentChild", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.UserModel", "Child")
                        .WithMany("ParentLinks")
                        .HasForeignKey("ChildId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyAI.Domain.Models.UserModel", "Parent")
                        .WithMany("ChildLinks")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Child");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ParentFlagRule", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.GlobalFlagRule", "GlobalRule")
                        .WithMany()
                        .HasForeignKey("GlobalRuleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAI.Domain.Models.UserModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("GlobalRule");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ParentScanSetting", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.UserModel", "Parent")
                        .WithMany()
                        .HasForeignKey("ParentUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ThreadFlagDetail", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.ChatLog", "Message")
                        .WithMany()
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FamilyAI.Domain.Models.ThreadScanResult", "ScanResult")
                        .WithMany("FlagDetails")
                        .HasForeignKey("ThreadScanResultId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("ScanResult");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ThreadModel", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ThreadScanResult", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.UserModel", "ScannedByParent")
                        .WithMany()
                        .HasForeignKey("ScannedByParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyAI.Domain.Models.ThreadModel", "Thread")
                        .WithMany()
                        .HasForeignKey("ThreadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ScannedByParent");

                    b.Navigation("Thread");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.UserPermission", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.Role", "Role")
                        .WithMany("UserPermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FamilyAI.Domain.Models.UserModel", "User")
                        .WithOne("UserPermissions")
                        .HasForeignKey("FamilyAI.Domain.Models.UserPermission", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.UserSetting", b =>
                {
                    b.HasOne("FamilyAI.Domain.Models.PromptTemplate", "PromptTemplate")
                        .WithMany()
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("FamilyAI.Domain.Models.UserModel", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("PromptTemplate");

                    b.Navigation("User");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.Role", b =>
                {
                    b.Navigation("UserPermissions");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ThreadModel", b =>
                {
                    b.Navigation("ChatLogs");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.ThreadScanResult", b =>
                {
                    b.Navigation("FlagDetails");
                });

            modelBuilder.Entity("FamilyAI.Domain.Models.UserModel", b =>
                {
                    b.Navigation("ChatLogs");

                    b.Navigation("ChildLinks");

                    b.Navigation("ParentLinks");

                    b.Navigation("UserPermissions");
                });
#pragma warning restore 612, 618
        }
    }
}
